services:
  - type: web
    name: solana-tracker
    env: node
    buildCommand: npm install
    startCommand: node src/server/index.js
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: MAIN_WALLET_PRIVATE_KEY
        sync: false